### ISSUE TITLE
《kubernetes进阶实战》堪误信息

### ISSUE THREAD

**Issue by iKubernetes** [iKubernetes/Kubernetes_Advanced_Practical#2]
欢迎《kubernetes进阶实战》的读者朋友们在此处提交堪误信息！

**Comment by iKubernetes** [comment]
欢迎《kubernetes进阶实战》的读者朋友们在此处提交堪误信息！

**Comment by faryang-sh** [comment]
![image](https://user-images.githubusercontent.com/14032423/56136915-4c503900-5fc6-11e9-844a-7ff98be7dff0.png)

**Comment by faryang-sh** [comment]
![image](https://user-images.githubusercontent.com/14032423/56150391-677c7200-5fe1-11e9-9ef0-046056b60fc8.png)

**Comment by faryang-sh** [comment]
![image](https://user-images.githubusercontent.com/14032423/56150556-bc1fed00-5fe1-11e9-976b-0bc9855b0233.png)

**Comment by jiangwh** [comment]
![image](https://user-images.githubusercontent.com/2804801/57568261-6808fc80-7417-11e9-9d69-973f2477016e.png)

**Comment by mrhan1993** [comment]
6.62章节，排版错误。应该在正文163页。（截图是微信读书购买的电子版，非D版）
![图片](https://user-images.githubusercontent.com/50648276/57747167-e52dbd80-7706-11e9-89e2-9fc6866a678d.png)

**Comment by lianghuiyuan** [comment]
<kubernetes进阶实战> 2019年1月第1版第1次印刷

- **第2章  2.1.2 Controller**  P19
书中描述多了一个~~DaemonSet~~：`控制器本身也是一种资源类型，它有着多种实现，其中与工作负载相关的实现如ReplicationController、Deployment、StatefulSet、DaemonSet、~~DaemonSet~~和Jobs等，也可统称他们为Pod控制器。……`

- **第7章  7.5.1 创建PV**  P187
书中描述：`下面的资源清单配置示例中定义了一个使用NFS存储后端的PV，空间大小为**10GB**，支持多路的读写操作。……`
但是YAML中PV创建的空间大小是**5GB**
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-0001
  labels:
    release: stable
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path:  "/webdata/htdocs"
    server: nfs.ikubernetes.io
```
- **第7章 7.5.4 存储类** P192
书中描述：“ `它定义了一个使用Gluster存储系统的存储类glusterfs，并通过**annotations**字段将其定义为默认的存储类：` ”
但是在glusterfs-storageclass.yaml文件中并没有`annotations`字段
**我认为这里是表述有误：annotations字段应该是用在定义PVC时将其使用的存储类默认为指定的存储类，但是我们本例中是定义存储类，这里不能通过annotations字段将其定义为默认的存储类。**
书中的**glusterfs-storageclass.yaml**文件：
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: gluster-dynamic
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://172.16.2.36:8080" 
  restauthenabled: "false"
```
- **第9章 9.1 StatefulSet概述**  P227~231
**这一小节写的真是乱啊[手动笑哭表情]！** 
https://github.com/iKubernetes/Kubernetes_Advanced_Practical/issues/2#issuecomment-483331022 和 https://github.com/iKubernetes/Kubernetes_Advanced_Practical/issues/2#issuecomment-483332048 提出了里面的错误，我也认为书中错了。

- **第12章 12.3.4 Pod反亲和性调度**  P342
创建反亲和性Pod对象时应该用podAntiAffinity，而不是podAffinity
书中YAML为：
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-with-pod-anti-affinity
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - {key: app, operator: In, values: ["myapp"]}
            topologyKey: kubernetes.io/hostname
      containers:
      - name: myapp
        image: ikubernetes/myapp:v1
```


正确的应该为：
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-with-pod-anti-affinity
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - {key: app, operator: In, values: ["myapp"]}
            topologyKey: kubernetes.io/hostname
      containers:
      - name: myapp
        image: ikubernetes/myapp:v1
```

**Comment by anxinyf** [comment]
第七章 7.5.2创建PVC P189-190
文章中不少yaml内容排版有问题...
第一、描述：**如果需要绑定此前创建的PV资源pv-rbd-0001**，而pvc-rbd-0001.yaml:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rbd-0001
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: fast
  selector:
    matchLabels:
      release: "stable"
```
但是在P88中给出的 pv-rbd-0001.yaml 中既没有metadata.labels.release: "stable",也没有spec.storageClassName: fast，这样时无法绑定的，而且该pv-rbd-0001.yaml 排版也有问题。但是github中已经给出[pv-rbd-0001.yaml](https://github.com/iKubernetes/Kubernetes_Advanced_Practical/blob/master/chapter7/pv-rbd-0001.yaml)，请注意！

第二、第七章 7.5.2P190 中一处描述为”persistentVolumeClain存储卷“ 应为”persistentVolumeClaim“
